config/routes.rb
Rails.application.routes.draw do


  get 'static_pages/apropos'
  get 'static_pages/home'
  resources :dons
  resources :charges
  root "dons#index"

  post "don/create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/don.rb
class Don < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @don = Don.find(params[:don_id])

  end

  def create
    @don = Don.find(params[:don_id])

    # Amount in cents
    @amount = @don.price.to_i * 100
  
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'eur'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/dons_controller.rb
class DonsController < ApplicationController
 before_action :find_don, only: [:show, :edit, :update, :destroy]
  def new
    #@don = Don.new

  end
  def index
    @don = Don.new
    #@dons = Don.all.order("created_at DESC")
    @total = 0
    prices = []
    Don.all.each{|don| prices << don.price.to_i }
    prices.each {|price| @total = @total + price}
    @pourcentage = @total*100/15000

    #@pbar = 0 #pbar bar de progression
    #bar = []
    #Don.all.each{|don| bar << pourcentage}
    #bar.each{|pourcentage| @pbar= @pbar + pourcentage}
    #@progressbar = @pbar*100/100

    @donor = Don.count

  end

  def create
    @don = Don.new(don_params)
    if @don.save
      redirect_to @don
    else
      render  "New"
    end

  end

  def show

  end

    private
  def don_params
    params.require(:don).permit(:price, :pseudo)
  end

  def find_don
   @don = Don.find(params[:id])
 end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def apropos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/dons_helper.rb
module DonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/charges/create.html.erb
<aside>
  <div class="row">
  <div class="col-md-offset-4 col-lg-4 col-md-4 col-sm-3 col-sx-10" id="zone">
        <h1 class="zone"> Mr ou Mme <%= @don.pseudo %> L'IPE et ses élèves vous remercient de votre don </h1>
        <div class="text-center">
    <h3><%= link_to "Retour à l'accueil", root_path, :class => "btn btn-primary" %></h3>
  </div>
  </div>
  </div>
</aside>

app/views/charges/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-lg-4 col-md-offset-4 col-md-4 col-xs-12" id="zone">
      <%= form_tag charges_path do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
          <h4>Vous pouvez dés à présent rentrer vos données bancaires en cliquant sur le lien ci-dessous </h4>
          <label class="amount">
            <!--<span><%= @don.price.to_i %></span>-->
          </label>
        </article>
         <%= hidden_field_tag :don_id,  @don.id %>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-label="Payez avec votre carte bleue"
                data-description="IPE don Ramadan"
                data-amount="<%= @don.price.to_i*100 %>"
                 data-currency ="eur"
                data-locale="auto"></script>
      <% end %>
    </div>
  </div>
</div>

app/views/dons/_form.html.erb
     <%= simple_form_for(@don, html: { class: 'form-horizontal', id: "add_plat" }) do |f| %>
      <%= f.text_field :pseudo , :placeholder => "Votre nom de Famille", class:"form-control"%>
      <%= f.text_field :price , :placeholder => "Votre don en euros", class:"form-control"%>
      <%= f.submit :value => "Validez",  :class =>"btn btn-secondary btn-lg btn-block" %>
    <% end%>

app/views/dons/index.html.erb
<div class="container">
    <section>
      <div class="row">
        <div class="text-center">
          <h1 class="title">Soutenons le collège</h1>
          <p class="text01">
            L'IPE et le collège Dina Morgabine ont besoin de vous. En ce mois béni
            de Ramadan,faites un don et oeuvrez pour l'au-dela.<br/> Le Prophète ( sur lui soit la paix)
            faisait preuve d'une grande générosité durant ce mois si particulier. <br/> Engagez-vous
            donc pour l'éducation de nos enfants en soutenant massivement ce projet réunionnais,
            Les familles <br/> nous font de plus en plus confiance, aidez-nous à être à la hauteur !
            Nous comptons sur vous !
            <br/>
          </p>
        </div>
      </div>
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12" id="video_zone">
        <div class="embed-responsive embed-responsive-4by3">
          <iframe width="560" height="315"
          src="https://www.youtube.com/embed/rxz1ulQu-J4"
          frameborder="0" allowfullscreen>
          </iframe>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12" id="zone_infos">
        <h2 class=title_mission>Soutenons l'IPE</h2>
          <h1 class="objectif">Objectif : <b>15000</b> €</h1>

        <h3>Financé à <br/><%= @pourcentage  %> % </h3>
        <h3>  <%= @donor %> Participants  </h3>
        <!--<%= button_to "Faire un don à l'IPE", new_don_path, :class =>
       "btn btn-secondary btn-lg btn-block", :method => :get %>-->
      </div>
    </div>
  </section>
</div>



  <div class="jumbotron" id="africa">
    <div class="container marketing" >
      <div class="row">
      <div class="text-center">
        <h1>Présentation de L'IPE </h1>
      </div>
    </div>
      <div class="row">
        <p  class="text-center">
        L'association IPE-Institut Privé d'Enseignement souhaite rendre à l'île de la Reunion
        et à ses habitants <br/> ce qu'ils nous ont tant donné depuis près de 150 ans. Protéger et renforcer
        son harmonie, <br/> promouvoir notre "reunionnité", proposer au monde notre témoignage...Un enjeu de
        taille que l'IPE souhaite relever.<br/>
        C'est dans cette optique que l'association décide de prendre sa part dans le défi de l'éducation
        et de la formation de notre jeunesse. En aout 2014, l'IPE ouvre un colège ouvert à tous,
        Dina Morgabin. Un nom chargé d'histoire, tel un rappel de nos racines...
        </p>
    </div>
    <!-- START THE FEATURETTES -->

     <hr class="featurette-divider">

     <div class="text-center">
       <h1 class="title_chiffre">Evènements culturels et sorties</h1>
     </div>
     <div class="row featurette">
       <div class="col-md-7">
         <h2 class="featurette-heading">Sortie scolaire</h2>
         <p class="lead">- En octobre 2016, une sortie a été organisée à St-Philippe à l'attention des élèves de CE2, CM1, et CM2
         du sud de l'île pour découvrir la richesse de la flore réunionnaise au "jardin des parfums et
         des épices".</p>
       </div>
       <div class="col-md-5">
         <img class="featurette-image img-responsive center-block" src="/balade.jpg" >
       </div>
     </div>

     <hr class="featurette-divider">

     <div class="row featurette">
       <div class="col-md-7 col-md-push-5">
         <h2 class="featurette-heading">Evènement culturel </h2>
         <p class="lead">Le 30 Avril 2017, une conférene assurée par une diététicienne-nutritionniste sur le thème
         de "Quelle alimentation pour la famille musulmane ?" à réuni une centaine de participantes à
         St-pierre.</p>
       </div>
       <div class="col-md-5 col-md-pull-7">
         <img class="featurette-image img-responsive center-block" src="/enfant_labo.jpg" >
       </div>
     </div>

     <hr class="featurette-divider">

     <!-- /END THE FEATURETTES -->

   </div>
   </div>


  <div class="container marketing" >
    <div class="text-center">
        <h1 class="title_chiffre">Projet d'établissement</h1>
        <h3>
          Notre projet se veut une contribution, avec d'autres à l'édification d'une société forte
          et meilleure. S'entraider à comprendre et à remplir son rôle dans cette vie, en
          comprenant ses besoins et en ayant le sens des priorités, est un grand défi
           et une grande responsabilité.
        </h3>
    </div>


    <div class="text-center">
        <h1 class="title_chiffre" id ="chiffres">Chiffres clés</h1>
    </div>
    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
      <div class="text-center">
        <i class="fa fa-child" aria-hidden="true"></i>

        <h2>Elèves</h2>
        <p>
          A la rentrée d'août 2017, l'établissement comptera près de 95 élèves in-cha Allah,
           avec l'ouverture d'une classe de 3ème et d'une classe de CM2;
        </p>

      </div>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
          <div class="text-center">
            <i class="fa fa-users" aria-hidden="true"></i>

            <h2> Professeurs</h2>
            <p>
              15 professeurs et intervenants salariés ou bénévoles constituent l'équipe
              pédagogique pilotée par un responsable pédagogique. Une place importante est donnée aux langues
              au sein du collège : La maitrise des langues est en effet indispensable pour la formation des
              "Zarboutans" du futur. L'anglais, l'arabe et l'espagnol sont ainsi enseignés.
            </p>
         </div>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
          <div class="text-center">
            <i class="fa fa-building" aria-hidden="true"></i>

            <h2>Administration</h2>
            <p>
              L'administration est constitué de quatre personnes qui sont dévoués pleinement à
              la reussite et la bonne gestion du collège.
            </p>
         </div>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-sx-12" id="paypay">
      <h1 class="text-pay">Comment faire un don ?</h1>
      <h3></h3>
      <h3 class="text-pay"><i class="fa fa-credit-card" aria-hidden="true"> Effectuez un don en ligne de manière sécurisé </i></h3>
      <h3 class="text-pay"><i class="fa fa-university" aria-hidden="true"> Par virement : <BR/><b>IBAN FR76 1871 9000 8300 0064 3600 044</b> </i></h3>
      <h3 class="text-pay"><i class="fa fa-pencil-square" aria-hidden="true"> Par chèque à l'ordre de <b>IPE </b><br/>40 rue victor le vigoureux St-pierre 97410</i></h3>
    </div>
      <div class="col-lg-6 col-md-6 col-sm-6 col-sx-12" id="zone_don">
        <h3 class="text_payment">Donnez via un paiement sécurisé</h3>
     <%= render "form"%>
      </div>
  </div>
</div>

app/views/dons/new.html.erb
<h1><%= render "form"%></h1>

app/views/dons/show.html.erb
<aside>
  <div class="row">
  <div class="col-md-offset-4 col-lg-4 col-md-4 col-sm-3 col-sx-10" id="zone">
        <h1 class="zone"> Mr ou Mme <%= @don.pseudo %> vous allez effectuer un don de <%= @don.price %> € </h1>
        <div class="text-center">
    <h3><%= link_to 'Passez au paiement', new_charge_path(don_id: @don.id), :class => "btn btn-primary" %></h3>
  </div>  
  </div>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="">
   <meta name="author" content="">
    <title>Don pour l'IPE  </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
  integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  </head>


  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a id="titre_site" class="navbar-brand" href="#header"><img id="logo" src="logo_ipe.png"></a>
       </div>
       <div id="navbar" class="navbar-collapse collapse">

         <ul class="nav navbar-nav navbar-right">
           <li>
              <a href="#" class="scroll-link" data-id="africa">Qui sommes nous </a>
           </li>
           <li>
               <a href="#" class="scroll-link" data-id="chiffres">Chiffres clés</a>
            </li >
           <li>
               <a href="#" class="scroll-link" data-id="contact">Contact</a>
            </li >
            <li>
               <a href="#" class="scroll-link" data-id="zone_don" role="button"><b>FAIRE UN DON</b></a>
             </li>

         </ul>
       </div>
     </div>
   </nav>

   <!--<nav class="navbar navbar-default" role="navigation">

      <div class="navbar-header centre">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a id="titre_site" class="navbar-brand" href="#header"><img id="logo" src="logo_ipe.png"></a>

      </div>


      <div class="collapse navbar-collapse navbar-ex1-collapse">

        <ul class="  nav navbar-nav navbar-right">
          <li>
             <a href="#" class="scroll-link" data-id="africa">Qui sommes nous </a>
          </li>
          <li>
              <a href="#" class="scroll-link" data-id="chiffres">Chiffres clés</a>
           <li >
          <li>
              <a href="#" class="scroll-link" data-id="contact">Contact</a>
           <li >
              <a href="#" class="scroll-link" data-id="zone_don" role="button"><b>FAIRE UN DON</b></a>

   </li>
        </ul>
      </div>
    </div>
  </nav>-->


    <%= yield %>

  <footer >
    <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6 footerleft " id ="contact">
        <div class="logofooter"> Qui nous sommes ?</div>
        <p>L'IPE est établissement privé d'enseignement de l'île de la reunion</p>
      </div>

      <div class="col-md-4 col-sm-6 paddingtop-bottom">
        <h6 class="heading7">Notre adresse</h6>
        <div class="post">
          <p><i class="fa fa-map-pin"></i> 40 rue victor le vigoureux St-pierre 97410,St-pierre de la reunion - France
          <p><i class="fa fa-phone"></i> Phone : 02 62 36 13 37</p>
          <p><i class="fa fa-envelope"></i> E-mail : contact@ipe.re</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 paddingtop-bottom">
        <a href="https://www.facebook.com/ipe.reunion?fref=ts">
          <img src="/facebook.png" border="0" alt="Link to this page", class="img_logo"> Visitez notre page facebook
        </a>
        <div class="fb-page" data-href="https://www.facebook.com/facebook" data-tabs="timeline" data-height="300" data-small-header="false" style="margin-bottom:15px;" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
        </div>
      </div>

      <div class="col-lg-offset-4 col-md-offset-4 col-sm-offset-4 col-xs-10">
        <h5><i class="fa fa-code" aria-hidden="true"></i> with <i class="fa fa-heart" aria-hidden="true"></i> by <a href ="https://twitter.com/jrkinouani" target="_blank">  jrkinouani</a></h5>
      </div>
    </div>
  </div>
</footer>
<!--footer start from here-->





    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>
            $(document).ready(function() {
        	// navigation click actions
        	$('.scroll-link').on('click', function(event){
        		event.preventDefault();
        		var sectionID = $(this).attr("data-id");
        		scrollToID('#' + sectionID, 750);
        	});
        	// scroll to top action
        	$('.scroll-top').on('click', function(event) {
        		event.preventDefault();
        		$('html, body').animate({scrollTop:0}, 'slow');
        	});
        	// mobile nav toggle
        	$('#nav-toggle').on('click', function (event) {
        		event.preventDefault();
        		$('#main-nav').toggleClass("open");
        	});
        });
        // scroll function

        // scroll function
          function scrollToID(id, speed){
          var offSet = 50;
          var targetOffset = $(id).offset().top - offSet;
          var mainNav = $('#main-nav');
          $('html,body').animate({scrollTop:targetOffset}, speed);
          if (mainNav.hasClass("open")) {
            mainNav.css("height", "1px").removeClass("in").addClass("collapse");
            mainNav.removeClass("open");
          }
          }
          if (typeof console === "undefined") {
            console = {
                log: function() { }
            };
          }
    </script>
  </body>
</html>

app/views/static_pages/apropos.html.erb
<h1>StaticPages#apropos</h1>
<p>Find me in app/views/static_pages/apropos.html.erb</p>

app/views/static_pages/home.html.erb
<div class="container">
  <section>
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
      <iframe width="760" height="415"
      src="https://www.youtube.com/embed/2BcaBGJbMrE"
      frameborder="0" allowfullscreen>
      </iframe>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <h2>Souvons l'IPE</h2>
    </div>
  </div>
</section>
</div>
<!--<header >
        <div class="container">
            <div class="row">
                <div class="text-center">
                  <h1 class="menu_typewrite">
                      <a href="" class="typewrite" data-period="2000"
                        data-type='[ "Installer un lavabo", "Renover une salle de bain", "Monter des étagères" ]'>
                        <span class="wrap"></span>
                      </a>
                    </h1>

                    <h2 class="slogan">MisterBrikol selectionne pour vos travaux <br>
                    les meilleures bricoleurs   pour une mise en relation <br>
                  par un simple sms</h2>

                    <h1>Contactez-nous par sms au <br> 06 93 15 99 93</h1>
                </div>
            </div>
        </div>
    </header>-->



    <div class="jumbotron">
      <div class="text-center">
        <h1></h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet.</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>
      </div>
     </div>


    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
        <div class="text-center">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->